### ISSUE TITLE
Error when use of other third party components in color component

### ISSUE THREAD

**Issue by yinshuxun** [docgeni/docgeni#272]
**Describe the bug**
I wirte a custom component depend on other modules in my custom component, where should I declare this dependency?

**To Reproduce**

### color.component.html
```
<ng-content></ng-content>
<aui-icon icon="spinner" style="font-size: 24px;"></aui-icon>
```
### color.component.ts
```
import { Component, ElementRef, HostBinding, Input, OnInit } from '@angular/core';
import { DocgeniBuiltInComponent } from '@docgeni/template';

@Component({
    selector: 'my-color',
    templateUrl: './color.component.html'
})
export class MyColorComponent extends DocgeniBuiltInComponent implements OnInit {
    @Input() set color(value: string) {
        this.hostElement.style.color = value;
    }

    constructor(elementRef: ElementRef<unknown>) {
        super(elementRef);
    }

    ngOnInit(): void {}
}

export default {
    selector: 'my-color',
    component: MyColorComponent
};
```
### My catalog screenshot：
![image](https://user-images.githubusercontent.com/18656086/139365813-93624c92-c996-4892-900d-1387fd62741c.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/18656086/139365476-940c4f4d-31cc-4226-bd0d-cdd79a7b85ef.png)

now, where can i to imports IconModule then to correctly use the aui-icon, I didn't find relevant instructions in the document

**Comment by why520crazy** [comment]
This is a missing feature to be implemented.

**Comment by why520crazy** [comment]
![image](https://user-images.githubusercontent.com/3959960/147543587-a34b03ee-5f05-48e9-b07d-d3c085797671.png)

please bump to `1.2.0-next.4` try it.
