### ISSUE TITLE
自定义组件如何使用FormsModule

### ISSUE THREAD

**Issue by yunyuyuan** [docgeni/docgeni#277]
.docgeni/component下面的自定义组件，如何使用类似FormsModule的第三方模块

**Comment by why520crazy** [comment]
same as #272 , this is a new feature

**Comment by why520crazy** [comment]
![image](https://user-images.githubusercontent.com/3959960/147543587-a34b03ee-5f05-48e9-b07d-d3c085797671.png)

please bump to `1.2.0-next.4` try it.
