### ISSUE TITLE
目前不支持 angular13 吗

### ISSUE THREAD

**Issue by chengdong1995** [docgeni/docgeni#292]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by why520crazy** [comment]
support Angular 13

**Comment by why520crazy** [comment]
[docgeni-template](https://github.com/docgeni/docgeni-template) 's angular has been upgraded to 13
