### ISSUE TITLE
@docgeni/cli 现在不支持ng13吧？

### ISSUE THREAD

**Issue by DawnSouther** [docgeni/docgeni#346]
**Describe the bug**
`npx @docgeni/cli init`执行报错

**Screenshots**
![image](https://user-images.githubusercontent.com/22205542/161367462-abf5141e-0abb-4150-a7ee-3eb77236c98b.png)
![image](https://user-images.githubusercontent.com/22205542/161367472-8d0d6746-0e36-46b6-82df-a0f0b43a40f6.png)
![image](https://user-images.githubusercontent.com/22205542/161367494-e218c554-b6a7-4d9f-8394-ccc9974d0f71.png)
![image](https://user-images.githubusercontent.com/22205542/161367499-bb75a54b-e4a0-4be5-83dc-402a32c438ba.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DawnSouther** [comment]
补一张npm i
![image](https://user-images.githubusercontent.com/22205542/161367783-87f55d5b-458a-45b6-8d4a-1c4efeabf2da.png)

**Comment by DawnSouther** [comment]
破案了，是1.2.0-next.10不支持，1.1.4版本还是支持angular@13.3.1的

**Comment by why520crazy** [comment]
> 破案了，是1.2.0-next.10不支持，1.1.4版本还是支持angular@13.3.1的

应该是缺陷，我们会尽快修复一下
