### ISSUE TITLE
如果多个类库存在相同名称组件（组件文件夹名称一样），文档路由对不上

### ISSUE THREAD

**Issue by woshiyc** [docgeni/docgeni#347]
**Describe the bug**
libs中如果两个库alib和blib，他们都有intro组件，在文档中点击alib和blib的intro目录，看到的都是alib的intro文档

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_2022_0414_162601.jpg](https://user-images.githubusercontent.com/39791324/163345328-afa767d7-7c14-43a4-9a5c-4228499bf27f.jpg)

**Desktop (please complete the following information):**
 - OS: [window]
 - Browser [chrome]
 - Version [1.2.0-next.4]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by why520crazy** [comment]
try upgrade to `1.2.0-next.11`
