### ISSUE TITLE
not support start fo auto create site...

### ISSUE THREAD

**Issue by aset1002** [docgeni/docgeni#358]
Angular -v  8.2.4 
docgeni -v  0.5.0

执行 npm run start:docs 后 卡在了这里 不知道什么情况
![image](https://user-images.githubusercontent.com/12155510/165248369-fa8593e9-c4c7-4981-acbe-fd636a17f68b.png)

**Comment by why520crazy** [comment]
0.5.0 版本不支持自动创建站点，请使用 `1.0.0` 版本吧

**Comment by why520crazy** [comment]
如果还是不行，建议最好升级 Angular ， Angular 8 基本不会花过多的时间维护
