### ISSUE TITLE
请问一下怎么样支持全文检索

### ISSUE THREAD

**Issue by a25154678** [docgeni/docgeni#361]
我目前遇到搜索得时候只能搜索到菜单
不能搜索到说明文档中得某段话

**Comment by why520crazy** [comment]
暂时不支持，使用 algolia 第三方服务搜索的话可以。

**Comment by a25154678** [comment]
后续能推出这个功能吗？

**Comment by a25154678** [comment]
并且有没有具体得时间日期

**Comment by why520crazy** [comment]
> 后续能推出这个功能吗？

这是一个纯前端的应用，支持内容搜索意味着要把所有内容加载出来，后续考虑一下可行性，未必会做
