### ISSUE TITLE
 BrowserModule has already been loaded

### ISSUE THREAD

**Issue by aset1002** [docgeni/docgeni#372]
执行完打包语句  docgeni build --configuration production 
然后启动服务后 控制台报错  
我已经检查过所有的mo模块了 没有重复import BrowserModule 模块
![image](https://user-images.githubusercontent.com/12155510/177693054-edbd4646-6854-44ec-b20c-e854514ff9f0.png)

**Comment by aset1002** [comment]
我认为是打包后 site/src/app/app.module.ts 里的 BrowserModule, BrowserAnimationsModule 引入导致了问题
![image](https://user-images.githubusercontent.com/12155510/177732601-29e2bad4-cead-47a7-913c-e0f39fdf33ea.png)

**Comment by why520crazy** [comment]
如果你其他地方没有导入不可能报错的，浏览器的模块必须在根模块导入，这里就是根模块

**Comment by why520crazy** [comment]
你可以先先手动把生成的根模块去掉浏览器模块试试，看看哪个地方用了

**Comment by aset1002** [comment]
我又检查了一遍 BrowserModule 没有导入。
只有一个地方导入CommonModule

**Comment by aset1002** [comment]
docgeni serve 启动后页面时正常的大
只有打包docgeni build后报错

**Comment by aset1002** [comment]
删除了.docgeni文件夹下site文件夹 重新build后问题解决了 
这个docgeni build 时不会先删除site文件夹 重建吗

**Comment by why520crazy** [comment]
Site 文件夹不会整体清除，会清除一些内部的文件夹，每次构建都会生成相关文件覆盖，不确定你这边是组件还是其他地方出的问题。
