### ISSUE TITLE
生成 “组件文档” 时提示路径引用错误

### ISSUE THREAD

**Issue by shiyuyuanfang** [docgeni/docgeni#414]
**Describe the bug**
生成 “组件文档” 时提示路径引用错误，并且识别自定义组件元素

**To Reproduce**
通过 cli 初始化一个名为 “my-app” 的angular项目，在通过 “ng add @docgeni/cli” 将 docgeni 添加到angular项目中后，按照以下步骤配置后报错；
[![image](https://user-images.githubusercontent.com/30991858/201570386-701befee-4558-4114-a641-2cc8cc468c67.png)](url)

**Expected behavior**
期望可以正常工作

**Comment by why520crazy** [comment]
确定一下 tsconfig.json 添加了 path 是否是站点 `.docgeni/public` 下的 tsconfig.json
https://docgeni.org/guides/basic/component#%E5%BC%95%E7%94%A8%E9%85%8D%E7%BD%AE

<img width="895" alt="image" src="https://user-images.githubusercontent.com/3959960/201582972-26dd3ecd-47c5-4b6a-b5d8-1f8367dfaaa9.png">

**Comment by why520crazy** [comment]
我看了一下，你把 `examples.module.ts` 改为 `module.ts` 试试

**Comment by why520crazy** [comment]
新版本已经支持自动生成 module.ts 
<img width="895" alt="image" src="https://user-images.githubusercontent.com/3959960/201583676-b957a265-73c9-4c8b-a7e5-f91ab77ea6c2.png">

**Comment by shiyuyuanfang** [comment]
非常感谢，这个问题已经得到解决;
