### ISSUE TITLE
docgeni 自定义 publicDir 目录时,ts 提示 enableIvy 必须有 override

### ISSUE THREAD

**Issue by xzfaith** [docgeni/docgeni#458]
## 运行`docgeni serve  --port 4600`提示
![image](https://user-images.githubusercontent.com/45060848/226503231-faff64aa-eaaa-4110-9eea-07d051ef8fb9.png)
## .docgenirc.js config
```javascript
/**
 * @type {import('@docgeni/core').DocgeniConfig}
 */
module.exports = {
  mode: "full",
  title: "前端",
  description: "",
  docsDir: "docs",
  publicDir: "public",
  navs: [null],
  libs: [],
};
```
## public 里 ts 配置
```json
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "extends": "../../tsconfig.json",
  "compilerOptions": { "strict": false, "sourceMap": true },
  "files": ["src/main.ts", "src/polyfills.ts"],
  "include": ["src/**/*.d.ts"]
}

```

**Comment by why520crazy** [comment]
你使用的是哪个版本？

**Comment by why520crazy** [comment]
我猜测你继承的 tsconfig.json  compilerOptions  中设置了 `noImplicitOverride: true` 所以导致了这个错误，你可以先设置 `noImplicitOverride` 为 false，或者单独给 public tsconfig 设置一下这个参数。

我会在之后的版本中，显示指定一下  enableIvy 为 override。

**Comment by xzfaith** [comment]
是的，目前单独给public tsconfig设置一下这个参数，可以正常运行呢
