### ISSUE TITLE
实现 HttpInterceptor，运行抛错

### ISSUE THREAD

**Issue by wfll17** [docgeni/docgeni#469]
**Describe the bug**
我的公共库里有一个文件，实现了angular的HttpInterceptor接口，当apiMode 设置为 "compatible"时，运行npm run start:docs 抛错。去掉implements HttpInterceptor就正常了。

版本：
angular-cli:13.2.5
docgeni:2.0.1

![](https://raw.githubusercontent.com/wfll17/images-folder/main/1571681283588_.pic.jpg)

**Comment by why520crazy** [comment]
fixed in `2.1.0-next.8`
