### ISSUE TITLE
can't support angular lastest version(15.2.6)

### ISSUE THREAD

**Issue by wangzhenghong** [docgeni/docgeni#476]
**Describe the bug**
ng upgrade 14 to 15,  will produce error:

HookWebpackError: Module build failed (from ../../node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
  │ @import '@manulife-design/md/styles/global/index.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/styles.scss 2:9  root stylesheet

./src/styles.scss - Error: Module build failed (from ../../node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
   │ @import '@manulife-design/md/styles/global/index.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/styles.scss 2:9  root stylesheet

**To Reproduce**
1. update angular to v15.2.x(@angular-devkit/build-angular)
2. npm run start
3. See error

**Expected behavior**
can support angular v 15.2.x

**Comment by why520crazy** [comment]
Can you check if this file `@manulife-design/md/styles/global/index.scss` exists ？

The angular version of repo https://github.com/docgeni/docgeni-template 's is `15.2.8`, it is ok!
