### ISSUE TITLE
When the default value of a boolean type property is false, it should not be recognized as -

### ISSUE THREAD

**Issue by minlovehua** [docgeni/docgeni#481]
布尔类型的属性的默认值识别：
能识别到   `@Input() @InputBoolean() thyAllowClear = true;`  默认值是 true。 没问题。
识别不到   `@Input() @InputBoolean() thyAutoFocus = false; ` 默认值是 false。  在API文档中默认值会展示成 `-` ，实际应该展示 `false`

**Comment by why520crazy** [comment]
这个是组件库吗？ 我记得已经修复了的

**Comment by minlovehua** [comment]
是基础组件库。刚刚看了下：是因为目前组件库的docgeni还在 ~2.1.1 所以没好，等基础组件库升到 2.2.0 就好了。
