### ISSUE TITLE
能否支持一下普通的class 和interface 注释呢

### ISSUE THREAD

**Issue by aimerthyr** [docgeni/docgeni#496]
![image](https://github.com/docgeni/docgeni/assets/44153856/a967b542-e8c7-40e0-9b90-b9fa2c5255ac)
这样子写，不会生成注释，是还需要什么配置嘛

**Comment by aimerthyr** [comment]
配置已经改成 apiMode: 'compatible'了，好像只有加了angular装饰器的内容才会被识别，普通的类和interface不会被识别

**Comment by aimerthyr** [comment]
@why520crazy 大佬有空帮忙看看嘛

**Comment by why520crazy** [comment]
https://docgeni.org/guides/basic/component

看这个文档，接口和Class需要显示标记为public 才会生成文档。

**Comment by aimerthyr** [comment]
我试了添加 public 或者 publicApi 还是不能生成文档
![image](https://github.com/docgeni/docgeni/assets/44153856/8b127f5e-53f7-4e4e-8f8a-069d21f1013d)
@why520crazy 咋回事呀

**Comment by why520crazy** [comment]
又在index导出吗？你看一下示例和你使用的区别吧
