### ISSUE TITLE
组件的公开函数不能生成文档

### ISSUE THREAD

**Issue by chensi66666** [docgeni/docgeni#504]
代码如下：
```ts
/**
 * 空组件
 * @public
 */
@Component({
    selector: 'ry-empty',
    standalone: true,
    templateUrl: './empty.component.html',
    styleUrls: ['./empty.component.scss']
})
export class EmptyComponent {

    /**
     * 撒的发生的
     * @param p1 s
     * @public
     */
    public test(p1: string) {
        return p1;
    }

}
```
文档如下：
![企业微信截图_16970812638968](https://github.com/docgeni/docgeni/assets/22761493/8e86eeef-c4be-47fe-8280-6f04b784d5ad)

**Comment by chensi66666** [comment]
它的使用场景是这样的。在使用一些公共组件时，会通过@ViewChild 拿到组件。然后调用组件的方法去做一些操作。如一些弹框的关闭，一些值的清除等。常见的一些组件库组件都有自己的方法。如 devExtreme 和 openTiny 等

**Comment by why520crazy** [comment]
please bump @docgnei/* to `2.2.1`
