### ISSUE TITLE
菜单排序无效 与 exclude 选项无效

### ISSUE THREAD

**Issue by HyperLife1119** [docgeni/docgeni#508]
**Describe the bug**

最小复现：https://github.com/HyperLife1119/docgeni-demo

![image](https://github.com/docgeni/docgeni/assets/41798664/908e5883-7b50-4491-a3d7-36026380d525)

1. 我为 `services/doc/en-us.md` 设置了 `order: 999`，services 目录应该排序到最后
2. 配置中已将 `src/exclude` 目录排除，但仍然被扫描到，生成了 API 文档

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by why520crazy** [comment]
1. 目前 include 是组件的根目录，比如指定了 `src` Docgeni 会把这个文件夹下的每个子文件夹当作一个组件生成文档，exclude 是排除哪个子文件夹，不需要带根目录的，只要 exclude 配置成 `['components', 'exclude']` 即可，这个后续可以做一下兼容处理，当待了根目录比如 `src/exclude` 也支持一下
2. 排序目前对于 Category 分类下的组件是支持的，但是示例中没有给组件加分类，所以这是一个缺陷，我会修复，目前临时的解决方案就是把 include "src/components", 放在前面

你调整一下类库的配置为：
```
libs: [
    {
      name: "test-lib",
      rootDir: "projects/test-lib",
      include: [
        "src/components",
        "src"
      ],
      exclude: [
        "components",
        "exclude"
      ],
      apiMode: "automatic",
      categories: [],
    },
  ],
```
这样结果就符合预期：
<img width="676" alt="image" src="https://github.com/docgeni/docgeni/assets/3959960/41a50c2a-14c1-4c24-ac38-99b3617d9320">
