### ISSUE TITLE
Error: Cannot read properties of undefined (reading '@docgei/angular')

### ISSUE THREAD

**Issue by zhanglp520** [docgeni/docgeni#526]
![image](https://github.com/docgeni/docgeni/assets/110772402/4c6159cd-323c-4cf2-8422-14fec1c51a25)

**Comment by zhanglp520** [comment]
是不是目前还不支持angular17.x？

**Comment by why520crazy** [comment]
这个错误看上去是 package.json 中的 devDependencies 没有配置，你这边方便提供你的项目 `package.json` 和目录结构吗？

The error appears to be due to the `devDependencies `not being configured in the `package.json`. Would you be able to provide your project's `package.json` and directory structure?

**Comment by miyou2024** [comment]
我也碰到这个问题了，我补充下我的场景：
1，首先我在一个空目录，提示：Error: Path "/package.json" does not exist
2，然后我尝试npm init 了一个空的  package.json，就报错  像标题那样
作者你好，我从文档中不确定应该从哪开始，或者说，需要有一个 angular的项目，然后在项目根目录中，执行 快速开始中的操作 嘛？
