### ISSUE TITLE
.docgeni/site/src/polyfills.ngtypecheck.ts' not found.

### ISSUE THREAD

**Issue by zhanglp520** [docgeni/docgeni#527]
![image](https://github.com/docgeni/docgeni/assets/110772402/127d8061-c1ff-4f6d-b9aa-31e9c5d4d3d0)

**Comment by zhanglp520** [comment]
build之后依然没有这个文件

**Comment by why520crazy** [comment]
最好提供一下完整的示例  demo

**Comment by why520crazy** [comment]
这是因为你在 `.docgeni/public` 下加了自定义的 tsconfig.json ，且 `includes` 中包含了 `polyfills.ts` ，去掉这个 json 或者`polyfills.ts`即可。
