### ISSUE TITLE
start:docs 运行时 出现 [ Data path "/polyfills" must be string]错误

### ISSUE THREAD

**Issue by qingqingzhufeng** [docgeni/docgeni#531]
可能是生成的site项目中angular.json的  
```
 "polyfills": [
              "zone.js"
            ],
```
为数组导致的，项目的angular版本为14。

**Comment by why520crazy** [comment]
Angular 14对应的 Docgeni不能是最新版本，你是使用的哪个版本

**Comment by qingqingzhufeng** [comment]
2.0 2.1 2.2 2.3 都试过，angular 13版本也试过，start:docs命令生成的site项目中，angualr.json中 
"polyfills": [
              "zone.js"
            ]
一项一直是数组，然后就报这个错

**Comment by why520crazy** [comment]
我这边看了一下 2.0.x 版本并不是数组，你尝试删除一下 site 缓存目录试试

Angular 14 版本对应的 template 示例项目为：https://github.com/docgeni/docgeni-template/tree/ng-14.x

<img width="1057" alt="image" src="https://github.com/docgeni/docgeni/assets/3959960/4ff7197a-51b5-4f78-85ea-2bea10f306b5">

你可以切换到这个分支试试

**Comment by mhtgogogo** [comment]
这个分支是1.几的版本
